Update .rancher-pipeline.yml file

diff --git a/.rancher-pipeline.yml b/.rancher-pipeline.yml
--- a/.rancher-pipeline.yml
+++ b/.rancher-pipeline.yml
@@ -42,7 +42,7 @@ stages:
       shellScript: |-
         #!/bin/bash
 
-        echo "hello world richa" | awk '{print ${3} }'
+        echo "hello world richa" | awk '{print $3}'
   when:
     event: {}
 - name: Test_postman
@@ -59,19 +59,28 @@ stages:
         - push
   - runScriptConfig:
       image: python:latest
-      shellScript: "apt-get update\napt-get install sshpass \n\n\n\n\n\n\n\n\n\nsshpass
-        -p mehant ssh -tt -o StrictHostKeyChecking=no mehant@192.168.100.178 << EOF\n\n\n\ndir=`pwd`\n\necho
-        \"Dir = ${dir}\"\n\npod_name=`kubectl --kubeconfig=config-176 get pods -n
-        updateandrollback |grep \"api-test\" |cut -d \" \" -f1|head -n1`\n\necho \"Pod
-        anme = ${pod_name}\"\n\n\nEOF\n\n\n"
+      shellScript: |+
+        # Stop on first error
+        #set -e;
+
+        docker run -t postman/newman:alpine run https://raw.githubusercontent.com/prabhat2410/Orion/master/Postman/CSP_Collection.postman_collection.json
+
+        status=$?
+
+        if [ "$status" != "0" ]; then
+          echo "Tests failed";
+          # build failed, don't deploy
+          exit 1;
+        else
+          echo "Tests passed";
+          # deploy build
+        fi
+
+
+
     when:
-      branch:
-        include:
-        - master
-      event:
-        include:
-        - pull_request
-        - push
+      branch: {}
+      event: {}
   when:
     event: {}
 - name: demo_test
