Update .rancher-pipeline.yml file

diff --git a/.rancher-pipeline.yml b/.rancher-pipeline.yml
--- a/.rancher-pipeline.yml
+++ b/.rancher-pipeline.yml
@@ -62,38 +62,14 @@ stages:
         - push
   - runScriptConfig:
       image: python:latest
-      shellScript: |+
-        # Stop on first error
-        #set -e;
-        apt-get update
-        apt-get install curl
-
-        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
-
-        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
-
-        apt-get update
-        apt-cache policy docker-ce
-
-        apt-get install -y docker-ce
-
-        systemctl status docker
-
-        docker run -t postman/newman:alpine run https://raw.githubusercontent.com/prabhat2410/Orion/master/Postman/CSP_Collection.postman_collection.json
-
-        status=$?
-
-        if [ "$status" != "0" ]; then
-          echo "Tests failed";
-          # build failed, don't deploy
-          exit 1;
-        else
-          echo "Tests passed";
-          # deploy build
-        fi
-
-
-
+      shellScript: "# Stop on first error\n#set -e;\napt-get update\napt-get install
+        \"software-properties-common\"\napt-get install curl\t\n\napt-get update\n\ncurl
+        -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -\n\nadd-apt-repository
+        \"deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable\"\n\napt-get
+        update\napt-cache policy docker-ce\n\napt-get install -y docker-ce\n\nsystemctl
+        status docker\n\ndocker run -t postman/newman:alpine run https://raw.githubusercontent.com/prabhat2410/Orion/master/Postman/CSP_Collection.postman_collection.json\n\nstatus=$?\n\nif
+        [ \"$status\" != \"0\" ]; then\n  echo \"Tests failed\";\n  # build failed,
+        don't deploy\n  exit 1;\nelse\n  echo \"Tests passed\";\n  # deploy build\nfi\n\n\n\n"
     when:
       branch: {}
       event: {}
